---
kind: pipeline
name: default

steps:
  - name: Check format
    image: ubuntu
    environment:
      CACHIX_TOKEN:
        from_secret: CACHEIX_TOKEN
    commands:
    - apt-get update -y
    - apt-get install curl xz-utils -y
    - addgroup --system nixbld
    - useradd -d /var/empty -g nixbld -G nixbld -M -N -r nixbld
    - mkdir -m 0755 /nix && chown nixbld /nix
    - curl -sSL https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install | bash
    - USER=root . /root/.nix-profile/etc/profile.d/nix.sh
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - nix-channel --update
    - nix-env -i nixpkgs-fmt bash jq tmate which
    - mkdir -p /usr/drone/bin/
    - ln -s $(which tmate) /usr/drone/bin/tmate
    - nixpkgs-fmt --check .
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix authtoken $CACHIX_TOKEN
    - bash build-cache.bash
    - nix build .#onedev
