---
kind: pipeline
name: default

steps:
  - name: Check format
    image: nixpkgs/nix-flakes
    environment:
      NIXPKGS: channel:nixos-unstable
      PATH: /root/.nix-profile/bin:/usr/bin:/bin:/nix/var/nix/profiles/default/bin
      CACHIX_TOKEN:
        from_secret: CACHEIX_TOKEN
    commands:
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - nix-channel --update
    - nix-env -i nixpkgs-fmt bash jq tmate which git
    - mkdir -p /usr/drone/bin/
    - ln -s $(which tmate) /usr/drone/bin/tmate
    - nixpkgs-fmt --check .
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
    - cachix authtoken $CACHIX_TOKEN
    - bash build-cache.bash
    - nix build .#onedev
