---
kind: template
load: .ci/build.yaml
data:
  node:
    os: nixos
    arch: amd64
    type: exec
    hostname: horizon
---
kind: template
load: .ci/build.yaml
data:
  node:
    os: nixos
    arch: aarch64
    type: exec
    hostname: oracle
