---
kind: pipeline
name: default
type: exec

trigger:
  branch:
  - master

steps:
- name: build
  environment:
    NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
    CACHIX_TOKEN:
      from_secret: CACHIX_TOKEN
  commands:
  - cachix authtoken $CACHIX_TOKEN
  - bash build-cache.bash

node:
  os: nixos
  arch: amd64
  type: exec
