stages:
- test
- build

nixpkgs-fmt:
  stage: test
  image: nixery.dev/shell/nixpkgs-fmt
  script:
  - nixpkgs-fmt --check .

.build:
  stage: build
  image: nixpkgs/nix-unstable
  variables:
    CACHIX_TOKEN: $CACHIX_TOKEN
  script:
  - bash build-cache.bash

build linux:
  extends:
  - .build

