tasks:
  - init: |
      direnv allow
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - bbenoist.nix
    - zhuangtongfa.material-theme
    - coenraads.bracket-pair-colorizer
    - donjayamanne.githistory
    - felipecaputo.git-project-manager
    - eamodio.gitlens
    - oderwat.indent-rainbow
    - wayou.vscode-todo-highlight
    - bungcip.better-toml
