[wgcf]
src.github = "ViRb3/wgcf"
fetch.github = "ViRb3/wgcf"
git.fetchSubmodules = true

[microsocks]
src.github = "rofl0r/microsocks"
fetch.github = "rofl0r/microsocks"
git.fetchSubmodules = true

[yacd]
src.github = "haishanh/yacd"
fetch.url = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"
git.fetchSubmodules = true

[yesplaymusic]
src.github = "qier222/YesPlayMusic"
src.prefix = "v"
fetch.url = "https://github.com/qier222/YesPlayMusic/releases/download/v$ver/YesPlayMusic-$ver.AppImage"

[chia-plotter]
src.git = "https://github.com/madMAx43v3r/chia-plotter.git"
fetch.github = "madMAx43v3r/chia-plotter"
git.fetchSubmodules = true

[cloudreve-cli]
src.git = "https://github.com/Indexyz/CloudreveCLI.git"
fetch.github = "Indexyz/CloudreveCLI"
git.fetchSubmodules = true

[fcitx5-material-color]
src.github = "hosxy/Fcitx5-Material-Color"
fetch.github = "hosxy/Fcitx5-Material-Color"
git.fetchSubmodules = true

[tifig]
src.git = "https://github.com/monostream/tifig.git"
fetch.github = "monostream/tifig"
git.fetchSubmodules = true

[desktop-icons-ng]
src.git = "https://gitlab.com/rastersoft/desktop-icons-ng.git"
fetch.git = "https://gitlab.com/rastersoft/desktop-icons-ng.git"
git.fetchSubmodules = true

[sunshine]
src.github = "loki-47-6F-64/sunshine"
fetch.github = "loki-47-6F-64/sunshine"
git.fetchSubmodules = true

[cloudreve]
src.github = "cloudreve/Cloudreve"
fetch.url = "https://github.com/cloudreve/Cloudreve/releases/download/$ver/cloudreve_$ver_linux_amd64.tar.gz"

[openwhisk-cli]
src.github = "apache/openwhisk-cli"
fetch.github = "apache/openwhisk-cli"
git.fetchSubmodules = true

[vpncloud]
src.github = "dswd/vpncloud"
fetch.github = "dswd/vpncloud"
git.fetchSubmodules = true

[winbox]
src.httpheader = "https://mikrotik.com/mt_redirect.php?code=winbox64"
src.regex = "\\/winbox\\/(.*)\\/"
fetch.url = "https://download.mikrotik.com/winbox/$ver/winbox64.exe"

[motrix]
src.github = "agalwood/Motrix"
src.prefix = "v"
fetch.url = "https://github.com/agalwood/Motrix/releases/download/v$ver/Motrix-$ver.AppImage"

[mmdb-ipip]
src.git = "https://github.com/alecthw/mmdb_china_ip_list.git"
fetch.git = "https://github.com/alecthw/mmdb_china_ip_list.git"
git.fetchSubmodules = true
src.branch = "release"

[drone-runner-exec]
src.github = "drone-runners/drone-runner-exec"
fetch.github = "drone-runners/drone-runner-exec"
git.fetchSubmodules = true

[drone-runner-docker]
src.github_tag = "drone-runners/drone-runner-docker"
fetch.github = "drone-runners/drone-runner-docker"
git.fetchSubmodules = true

[nali]
src.github = "zu1k/nali"
fetch.github = "zu1k/nali"
git.fetchSubmodules = true

[wiretrustee]
src.github = "wiretrustee/wiretrustee"
fetch.github = "wiretrustee/wiretrustee"
git.fetchSubmodules = true

[mattermost]
src.webpage = "https://mattermost.com/deploy/"
src.regex = "<strong>Latest Release: </strong>(.*)</span>"
fetch.url = "https://releases.mattermost.com/$ver/mattermost-$ver-linux-amd64.tar.gz"

[ksmbd]
src.git = "https://github.com/namjaejeon/ksmbd.git"
fetch.github = "namjaejeon/ksmbd"
git.fetchSubmodules = true

[ksmbd-tools]
src.git = "https://github.com/namjaejeon/ksmbd-tools.git"
fetch.github = "namjaejeon/ksmbd-tools"
git.fetchSubmodules = true

[vouch]
src.github_tag = "vouch/vouch-proxy"
fetch.github = "vouch/vouch-proxy"
git.fetchSubmodules = true

[gost]
src.git = "https://github.com/ginuerzh/gost.git"
fetch.github = "ginuerzh/gost"
git.fetchSubmodules = true
