[yacd]
src.github = "haishanh/yacd"
fetch.url = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"
git.fetchSubmodules = true

[yesplaymusic]
src.github = "qier222/YesPlayMusic"
src.prefix = "v"
fetch.url = "https://github.com/qier222/YesPlayMusic/releases/download/v$ver/YesPlayMusic-$ver.AppImage"

[sunshine]
src.github = "loki-47-6F-64/sunshine"
fetch.github = "loki-47-6F-64/sunshine"
git.fetchSubmodules = true

[cloudreve]
src.github = "cloudreve/Cloudreve"
fetch.url = "https://github.com/cloudreve/Cloudreve/releases/download/$ver/cloudreve_$ver_linux_amd64.tar.gz"

[motrix]
src.github = "agalwood/Motrix"
src.prefix = "v"
fetch.url = "https://github.com/agalwood/Motrix/releases/download/v$ver/Motrix-$ver.AppImage"
