[microsocks]
src.github = "rofl0r/microsocks"
fetch.github = "rofl0r/microsocks"
git.fetchSubmodules = true

[yacd]
src.github = "haishanh/yacd"
fetch.url = "https://github.com/haishanh/yacd/releases/download/$ver/yacd.tar.xz"
git.fetchSubmodules = true

[yesplaymusic]
src.github = "qier222/YesPlayMusic"
src.prefix = "v"
fetch.url = "https://github.com/qier222/YesPlayMusic/releases/download/v$ver/YesPlayMusic-$ver.AppImage"

[fcitx5-material-color]
src.github = "hosxy/Fcitx5-Material-Color"
fetch.github = "hosxy/Fcitx5-Material-Color"
git.fetchSubmodules = true

[sunshine]
src.github = "loki-47-6F-64/sunshine"
fetch.github = "loki-47-6F-64/sunshine"
git.fetchSubmodules = true

[cloudreve]
src.github = "cloudreve/Cloudreve"
fetch.url = "https://github.com/cloudreve/Cloudreve/releases/download/$ver/cloudreve_$ver_linux_amd64.tar.gz"

[vpncloud]
src.github = "dswd/vpncloud"
fetch.github = "dswd/vpncloud"
git.fetchSubmodules = true
cargo_locks = ["Cargo.lock"]

[winbox]
src.httpheader = "https://mikrotik.com/mt_redirect.php?code=winbox64"
src.regex = "\\/winbox\\/(.*)\\/"
fetch.url = "https://download.mikrotik.com/winbox/$ver/winbox64.exe"

[motrix]
src.github = "agalwood/Motrix"
src.prefix = "v"
fetch.url = "https://github.com/agalwood/Motrix/releases/download/v$ver/Motrix-$ver.AppImage"

[mmdb-ipip]
src.git = "https://github.com/alecthw/mmdb_china_ip_list.git"
fetch.git = "https://github.com/alecthw/mmdb_china_ip_list.git"
git.fetchSubmodules = true
src.branch = "release"

[nali]
src.manual = "v0.3.2"
fetch.github = "zu1k/nali"
git.fetchSubmodules = true

[mattermost]
src.webpage = "https://mattermost.com/deploy/"
src.regex = "mattermost-(.*)-linux-amd64.tar.gz"
fetch.url = "https://releases.mattermost.com/$ver/mattermost-$ver-linux-amd64.tar.gz"

[ksmbd]
src.git = "https://github.com/namjaejeon/ksmbd.git"
fetch.github = "namjaejeon/ksmbd"
git.fetchSubmodules = true

[ksmbd-tools]
src.git = "https://github.com/namjaejeon/ksmbd-tools.git"
fetch.github = "namjaejeon/ksmbd-tools"
git.fetchSubmodules = true

[clash-premium]
src.webpage = "https://github.com/Dreamacro/clash/releases/tag/premium"
src.regex = "Premium ([0-9\\.]*)"
fetch.url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-$ver.gz"

[edl]
src.git = "https://github.com/bkerler/edl.git"
fetch.github = "bkerler/edl"
git.fetchSubmodules = true

[tun2socks]
src.github = "xjasonlyu/tun2socks"
fetch.github = "xjasonlyu/tun2socks"
git.fetchSubmodules = true

[commit-notifier]
src.git = "https://github.com/linyinfeng/commit-notifier.git"
fetch.github = "linyinfeng/commit-notifier"
git.fetchSubmodules = true
cargo_locks = ["Cargo.lock"]

[simple-obfs]
src.github = "shadowsocks/simple-obfs"
fetch.github = "shadowsocks/simple-obfs"
git.fetchSubmodules = true

[wechat-uos]
src.manual = "2.1.3"
fetch.url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_$ver_amd64.deb"

[realm]
src.github = "zhboner/realm"
fetch.github = "zhboner/realm"
git.fetchSubmodules = true
cargo_locks = ["Cargo.lock"]

[trojan-go]
src.github = "p4gefau1t/trojan-go"
fetch.github = "p4gefau1t/trojan-go"
git.fetchSubmodules = true

[landrop]
src.github = "LANDrop/LANDrop"
fetch.github = "LANDrop/LANDrop"

[hev-socks5-tproxy]
src.github_tag = "heiher/hev-socks5-tproxy"
fetch.github = "heiher/hev-socks5-tproxy"
git.fetchSubmodules = true
