# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  wgcf = {
    pname = "wgcf";
    version = "v2.2.3";
    src = fetchgit {
      url = "https://github.com/ViRb3/wgcf";
      rev = "v2.2.3";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1j059ddwf8s0vl633pp6hq4csxpli3akwf8ny2j849pays3ibdnn";
    };
  };
}
