# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  chia-plotter = {
    pname = "chia-plotter";
    version = "974d6e5f1440f68c48492122ca33828a98864dfc";
    src = fetchgit {
      url = "https://github.com/madMAx43v3r/chia-plotter";
      rev = "974d6e5f1440f68c48492122ca33828a98864dfc";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0dliswvqmi3wq9w8jp0sb0z74n5k37608sig6r60z206g2bwhjja";
    };
  };
  cloudreve-cli = {
    pname = "cloudreve-cli";
    version = "456d8c4403efea11e4584067419f8f20a8682e06";
    src = fetchgit {
      url = "https://github.com/Indexyz/CloudreveCLI";
      rev = "456d8c4403efea11e4584067419f8f20a8682e06";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0dxhwaxrzg5vqgyh0cy4g68r5xsdn0489k92b2ypclg5paq1zrci";
    };
  };
  microsocks = {
    pname = "microsocks";
    version = "v1.0.2";
    src = fetchgit {
      url = "https://github.com/rofl0r/microsocks";
      rev = "v1.0.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1di11wx9ihwa0g9qzsqrb3ka2xxjb10fyc7hwjhn58mxdfwlavl0";
    };
  };
  wgcf = {
    pname = "wgcf";
    version = "v2.2.5";
    src = fetchgit {
      url = "https://github.com/ViRb3/wgcf";
      rev = "v2.2.5";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0vvjywsigh9j669zd2blsnhlz5kjv4j39g33hclj2a7i44dwg13h";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.3";
    src = fetchgit {
      url = "https://github.com/haishanh/yacd";
      rev = "v0.3.3";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0b2rwnn8rffnhhdmhjmd8wanxkslivnpxxs9y4k7b7h1abmgc6j4";
    };
  };
}
