# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  clash-premium = {
    pname = "clash-premium";
    version = "2022.06.19";
    src = fetchurl {
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.06.19.gz";
      sha256 = "sha256-ASB9ehUjiEdwnVcOfZWVSjkVdlAYg/qOVzjmyNoDVzU=";
    };
  };
  cloudreve = {
    pname = "cloudreve";
    version = "3.5.3";
    src = fetchurl {
      url = "https://github.com/cloudreve/Cloudreve/releases/download/3.5.3/cloudreve_3.5.3_linux_amd64.tar.gz";
      sha256 = "sha256-RGlo99nmffTNc85syPGY7VIkCRPqDrN+KC2oMoBWGDQ=";
    };
  };
  commit-notifier = {
    pname = "commit-notifier";
    version = "573c1eb7eabc97aa06e0e9ad85f5148110749876";
    src = fetchFromGitHub ({
      owner = "linyinfeng";
      repo = "commit-notifier";
      rev = "573c1eb7eabc97aa06e0e9ad85f5148110749876";
      fetchSubmodules = true;
      sha256 = "sha256-JiLwijB+Zqe5JgKLncr7r4w1lpDRWWVh9TAl+9nOiCo=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./commit-notifier-573c1eb7eabc97aa06e0e9ad85f5148110749876/Cargo.lock;
      outputHashes = { };
    };
  };
  drone-runner-docker = {
    pname = "drone-runner-docker";
    version = "v1.8.2";
    src = fetchFromGitHub ({
      owner = "drone-runners";
      repo = "drone-runner-docker";
      rev = "v1.8.2";
      fetchSubmodules = true;
      sha256 = "sha256-ZpkVfzqeltZSYrKYB6dXtlVjl1uFpQdl2fa+c5ApiW4=";
    });
  };
  drone-runner-exec = {
    pname = "drone-runner-exec";
    version = "v1.0.0-beta.9";
    src = fetchFromGitHub ({
      owner = "drone-runners";
      repo = "drone-runner-exec";
      rev = "v1.0.0-beta.9";
      fetchSubmodules = true;
      sha256 = "sha256-upP6e/I5FRF+WEp086T1NmQA8YXcMG9VHixDUhTdxKs=";
    });
  };
  edl = {
    pname = "edl";
    version = "cecfcb44b168e4c808bcf5b2d1cafca66ca97e0e";
    src = fetchFromGitHub ({
      owner = "bkerler";
      repo = "edl";
      rev = "cecfcb44b168e4c808bcf5b2d1cafca66ca97e0e";
      fetchSubmodules = true;
      sha256 = "sha256-8bNxIQwj7lV1jTEcutBM3dGo972S0i7+gmyvjRkKfwc=";
    });
  };
  fcitx5-material-color = {
    pname = "fcitx5-material-color";
    version = "0.2.1";
    src = fetchFromGitHub ({
      owner = "hosxy";
      repo = "Fcitx5-Material-Color";
      rev = "0.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-i9JHIJ+cHLTBZUNzj9Ujl3LIdkCllTWpO1Ta4OT1LTc=";
    });
  };
  gost = {
    pname = "gost";
    version = "0247b941ac31344f0d7b3c547941a051188ba202";
    src = fetchFromGitHub ({
      owner = "ginuerzh";
      repo = "gost";
      rev = "0247b941ac31344f0d7b3c547941a051188ba202";
      fetchSubmodules = true;
      sha256 = "sha256-GYFWEHt1CNoKvdcQh0fEU/BH3Go85RrIwUZb3EUZeSI=";
    });
  };
  ksmbd = {
    pname = "ksmbd";
    version = "1a05840d763d3339bd70fc28187f51ca4f6b5804";
    src = fetchFromGitHub ({
      owner = "namjaejeon";
      repo = "ksmbd";
      rev = "1a05840d763d3339bd70fc28187f51ca4f6b5804";
      fetchSubmodules = true;
      sha256 = "sha256-W4d+ykVKf9wx+yRcsZLP/FIshkJcYZBsUNJ0GFEBlKE=";
    });
  };
  ksmbd-tools = {
    pname = "ksmbd-tools";
    version = "040e1933fcee474a27bf79729ce9059f86184e8d";
    src = fetchFromGitHub ({
      owner = "namjaejeon";
      repo = "ksmbd-tools";
      rev = "040e1933fcee474a27bf79729ce9059f86184e8d";
      fetchSubmodules = true;
      sha256 = "sha256-8KZqcD52gSNSw5rx5jqMeBdnaPR1iwv8CwklMCi8apo=";
    });
  };
  landrop = {
    pname = "landrop";
    version = "v0.4.0";
    src = fetchFromGitHub ({
      owner = "LANDrop";
      repo = "LANDrop";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-IwtphjMSa0e2mO5C4zHId48SUpT99sXziZzApnSmvrU=";
    });
  };
  mattermost = {
    pname = "mattermost";
    version = "7.0.0";
    src = fetchurl {
      url = "https://releases.mattermost.com/7.0.0/mattermost-7.0.0-linux-amd64.tar.gz";
      sha256 = "sha256-O2bJsj2YjeaRfqPrehgwn8bNHaYwqcrcU1htCYurPlw=";
    };
  };
  microsocks = {
    pname = "microsocks";
    version = "v1.0.3";
    src = fetchFromGitHub ({
      owner = "rofl0r";
      repo = "microsocks";
      rev = "v1.0.3";
      fetchSubmodules = true;
      sha256 = "sha256-l+8+zqeY/Qf5pKvzW9WQBfltEvrD7Vp+hJAXM2o16aI=";
    });
  };
  mmdb-ipip = {
    pname = "mmdb-ipip";
    version = "08c2278e0a8f07d32e3487212daedf0b6901f63a";
    src = fetchgit {
      url = "https://github.com/alecthw/mmdb_china_ip_list.git";
      rev = "08c2278e0a8f07d32e3487212daedf0b6901f63a";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-UjK5DztspCh+uSmn+I2IrY5yNiCsHt+xABFUMw2takM=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  nali = {
    pname = "nali";
    version = "v0.3.2";
    src = fetchFromGitHub ({
      owner = "zu1k";
      repo = "nali";
      rev = "v0.3.2";
      fetchSubmodules = true;
      sha256 = "sha256-iRLoUBA+Kzv1/LZQ8HCvR79K1riYErxEWhB0OmvFy2g=";
    });
  };
  nearcore = {
    pname = "nearcore";
    version = "1.26.1";
    src = fetchFromGitHub ({
      owner = "near";
      repo = "nearcore";
      rev = "1.26.1";
      fetchSubmodules = true;
      sha256 = "sha256-WoQtDdbFcvl6Wp5uv2tr/W/YYH8dyezF+LzSJ5oJcYY=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./nearcore-1.26.1/Cargo.lock;
      outputHashes = {
        "paperclip-0.5.0" = "sha256-oQHrsXtd+PW8Ogfs9NM1oBg2wwa+hCBu/3LyMxghEIY=";
        "sysinfo-0.14.3" = "sha256-3oay53OBILdA3HULGCYway65JDLwcQSl898sWCAgwls=";
        "actix-cors-0.6.0-beta.2" = "sha256-0llqozO0wS/33jXyDUqxTNTcs7SDL9KVzBznF0IIWoQ=";
      };
    };
  };
  openwhisk-cli = {
    pname = "openwhisk-cli";
    version = "1.2.0";
    src = fetchFromGitHub ({
      owner = "apache";
      repo = "openwhisk-cli";
      rev = "1.2.0";
      fetchSubmodules = true;
      sha256 = "sha256-SdsfRuN4tsuTObETrES8VOrn2jgz3SucMXKvyUuuZYs=";
    });
  };
  pufferpanel = {
    pname = "pufferpanel";
    version = "v2.5.0";
    src = fetchFromGitHub ({
      owner = "PufferPanel";
      repo = "PufferPanel";
      rev = "v2.5.0";
      fetchSubmodules = true;
      sha256 = "sha256-5skA4ygVwQIf1IB3+odF8QYqYJ6yx9g1v/XORKesHIo=";
    });
  };
  realm = {
    pname = "realm";
    version = "v2.3.6";
    src = fetchFromGitHub ({
      owner = "zhboner";
      repo = "realm";
      rev = "v2.3.6";
      fetchSubmodules = true;
      sha256 = "sha256-1xcHKjaaJ3GA77dl57NwVJTl5dW2EP93+5leOGJPDs0=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./realm-v2.3.6/Cargo.lock;
      outputHashes = { };
    };
  };
  simple-obfs = {
    pname = "simple-obfs";
    version = "v0.0.5";
    src = fetchFromGitHub ({
      owner = "shadowsocks";
      repo = "simple-obfs";
      rev = "v0.0.5";
      fetchSubmodules = true;
      sha256 = "sha256-xNkIAltV+NnV+kgKZv8UZaeefjaVt35m+UjU+gbDQEw=";
    });
  };
  sunshine = {
    pname = "sunshine";
    version = "v0.11.1";
    src = fetchFromGitHub ({
      owner = "loki-47-6F-64";
      repo = "sunshine";
      rev = "v0.11.1";
      fetchSubmodules = true;
      sha256 = "sha256-YrQHHpw7GOcdlnyJI28VShYFrTRq7kpILnkyCYf77NE=";
    });
  };
  trojan-go = {
    pname = "trojan-go";
    version = "v0.10.6";
    src = fetchFromGitHub ({
      owner = "p4gefau1t";
      repo = "trojan-go";
      rev = "v0.10.6";
      fetchSubmodules = true;
      sha256 = "sha256-ZzIEKyLhHwYEWBfi6fHlCbkEImetEaRewbsHQEduB5Y=";
    });
  };
  tun2socks = {
    pname = "tun2socks";
    version = "v2.4.1";
    src = fetchFromGitHub ({
      owner = "xjasonlyu";
      repo = "tun2socks";
      rev = "v2.4.1";
      fetchSubmodules = true;
      sha256 = "sha256-FBYRqxS8DJbIc8j8X6WNxl6a1YRcNrPSnNfrq/Y0fMM=";
    });
  };
  vouch = {
    pname = "vouch";
    version = "v0.37.0";
    src = fetchFromGitHub ({
      owner = "vouch";
      repo = "vouch-proxy";
      rev = "v0.37.0";
      fetchSubmodules = true;
      sha256 = "sha256-sBbA4uRpCiEPw1D2dxnyHYQZ7JLWlY+OJzu1sscqjGU=";
    });
  };
  vpncloud = {
    pname = "vpncloud";
    version = "v2.3.0";
    src = fetchFromGitHub ({
      owner = "dswd";
      repo = "vpncloud";
      rev = "v2.3.0";
      fetchSubmodules = true;
      sha256 = "sha256-74ohjWnBHr31sM08ghFWnrfIRjfQ5M7nrKi0yT/cGEo=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./vpncloud-v2.3.0/Cargo.lock;
      outputHashes = { };
    };
  };
  wechat-uos = {
    pname = "wechat-uos";
    version = "2.1.3";
    src = fetchurl {
      url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_2.1.3_amd64.deb";
      sha256 = "sha256-W3ckVWbmgpwrIjsEFz80wcN853CdIu1NiiR1czjPsKM=";
    };
  };
  wgcf = {
    pname = "wgcf";
    version = "v2.2.15";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "v2.2.15";
      fetchSubmodules = true;
      sha256 = "sha256-tUEeczs3J//2ZrZkAsSn3C+GScRPaIgheRM2wByS8p4=";
    });
  };
  winbox = {
    pname = "winbox";
    version = "3.36";
    src = fetchurl {
      url = "https://download.mikrotik.com/winbox/3.36/winbox64.exe";
      sha256 = "sha256-PRbidXHwVBoOBP+nw/GC6KoqKyYAFgOLgODCP4tObTA=";
    };
  };
  wiretrustee = {
    pname = "wiretrustee";
    version = "v0.7.0";
    src = fetchFromGitHub ({
      owner = "wiretrustee";
      repo = "wiretrustee";
      rev = "v0.7.0";
      fetchSubmodules = true;
      sha256 = "sha256-DBghmychU261Zy2NF6EHgoB7jwQgazf19VQ0iqUz7GI=";
    });
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.5";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.5/yacd.tar.xz";
      sha256 = "sha256-j2sDOC7QqoP0ptQ9cKa6kHM2efid7kgNmsggODEQaSA=";
    };
  };
  yesplaymusic = {
    pname = "yesplaymusic";
    version = "0.4.5";
    src = fetchurl {
      url = "https://github.com/qier222/YesPlayMusic/releases/download/v0.4.5/YesPlayMusic-0.4.5.AppImage";
      sha256 = "sha256-9Jj4VqrEIsx2oFUoQaPEKaEcyKDR5SQF9tJ2r2w62CM=";
    };
  };
}
