# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  clash-premium = {
    pname = "clash-premium";
    version = "2022.07.07";
    src = fetchurl {
      url = "https://github.com/Dreamacro/clash/releases/download/premium/clash-linux-amd64-2022.07.07.gz";
      sha256 = "sha256-JmGP9ziouzSQFI1kvpM+ejmQibKP8UNPDXhmNkBCWi8=";
    };
  };
  cloudreve = {
    pname = "cloudreve";
    version = "3.5.3";
    src = fetchurl {
      url = "https://github.com/cloudreve/Cloudreve/releases/download/3.5.3/cloudreve_3.5.3_linux_amd64.tar.gz";
      sha256 = "sha256-RGlo99nmffTNc85syPGY7VIkCRPqDrN+KC2oMoBWGDQ=";
    };
  };
  commit-notifier = {
    pname = "commit-notifier";
    version = "573c1eb7eabc97aa06e0e9ad85f5148110749876";
    src = fetchFromGitHub ({
      owner = "linyinfeng";
      repo = "commit-notifier";
      rev = "573c1eb7eabc97aa06e0e9ad85f5148110749876";
      fetchSubmodules = true;
      sha256 = "sha256-JiLwijB+Zqe5JgKLncr7r4w1lpDRWWVh9TAl+9nOiCo=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./commit-notifier-573c1eb7eabc97aa06e0e9ad85f5148110749876/Cargo.lock;
      outputHashes = { };
    };
  };
  drone-runner-docker = {
    pname = "drone-runner-docker";
    version = "v1.8.2";
    src = fetchFromGitHub ({
      owner = "drone-runners";
      repo = "drone-runner-docker";
      rev = "v1.8.2";
      fetchSubmodules = true;
      sha256 = "sha256-ZpkVfzqeltZSYrKYB6dXtlVjl1uFpQdl2fa+c5ApiW4=";
    });
  };
  drone-runner-exec = {
    pname = "drone-runner-exec";
    version = "v1.0.0-beta.10";
    src = fetchFromGitHub ({
      owner = "drone-runners";
      repo = "drone-runner-exec";
      rev = "v1.0.0-beta.10";
      fetchSubmodules = true;
      sha256 = "sha256-dQIN0DXH9j4Qu0Q8vwHjTG/lrtThHnR2bc1UymuUACI=";
    });
  };
  edl = {
    pname = "edl";
    version = "2c2eeddf6684ec03347b5c7fda1f879ce188823e";
    src = fetchFromGitHub ({
      owner = "bkerler";
      repo = "edl";
      rev = "2c2eeddf6684ec03347b5c7fda1f879ce188823e";
      fetchSubmodules = true;
      sha256 = "sha256-dcnMwi+yHs/GEk3E2Ne7dVVoUzG6Wi9XS+KcRyOU/1s=";
    });
  };
  fcitx5-material-color = {
    pname = "fcitx5-material-color";
    version = "0.2.1";
    src = fetchFromGitHub ({
      owner = "hosxy";
      repo = "Fcitx5-Material-Color";
      rev = "0.2.1";
      fetchSubmodules = true;
      sha256 = "sha256-i9JHIJ+cHLTBZUNzj9Ujl3LIdkCllTWpO1Ta4OT1LTc=";
    });
  };
  gost = {
    pname = "gost";
    version = "81854a61e0c169b33ae060c3238c83711c432686";
    src = fetchFromGitHub ({
      owner = "ginuerzh";
      repo = "gost";
      rev = "81854a61e0c169b33ae060c3238c83711c432686";
      fetchSubmodules = true;
      sha256 = "sha256-FOGtCZqJ/JZ8LSoKv/7LCbOOMJakyHjA3DCuNHD873c=";
    });
  };
  guestfs-tools = {
    pname = "guestfs-tools";
    version = "6b81746649cf586c9783fa4f82b0fce138df00f1";
    src = fetchFromGitHub ({
      owner = "rwmjones";
      repo = "guestfs-tools";
      rev = "6b81746649cf586c9783fa4f82b0fce138df00f1";
      fetchSubmodules = true;
      sha256 = "sha256-eHlSUsZnQ+Pr+olf9mtAr57qD6+rSRKQnIdwWAAMNPQ=";
    });
  };
  ksmbd = {
    pname = "ksmbd";
    version = "ca468bb1f74598a016ec1cc022229272d243956e";
    src = fetchFromGitHub ({
      owner = "namjaejeon";
      repo = "ksmbd";
      rev = "ca468bb1f74598a016ec1cc022229272d243956e";
      fetchSubmodules = true;
      sha256 = "sha256-FCdABXzcFyI25pGxWIkefwH3H3KRcI3VWS79np+7Vb4=";
    });
  };
  ksmbd-tools = {
    pname = "ksmbd-tools";
    version = "c3ea65643fb5143808ac866c6ce0154dc59c3930";
    src = fetchFromGitHub ({
      owner = "namjaejeon";
      repo = "ksmbd-tools";
      rev = "c3ea65643fb5143808ac866c6ce0154dc59c3930";
      fetchSubmodules = true;
      sha256 = "sha256-Gi89++gwaHC6mXH38VJqJpNoPtfpZEXKBiBhNFN+fB4=";
    });
  };
  landrop = {
    pname = "landrop";
    version = "v0.4.0";
    src = fetchFromGitHub ({
      owner = "LANDrop";
      repo = "LANDrop";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-IwtphjMSa0e2mO5C4zHId48SUpT99sXziZzApnSmvrU=";
    });
  };
  mattermost = {
    pname = "mattermost";
    version = "7.2.0";
    src = fetchurl {
      url = "https://releases.mattermost.com/7.2.0/mattermost-7.2.0-linux-amd64.tar.gz";
      sha256 = "sha256-FATtO6xFa/bKwywyhKEFZgrle0QPKZI8BQbrA3IlPRg=";
    };
  };
  microsocks = {
    pname = "microsocks";
    version = "v1.0.3";
    src = fetchFromGitHub ({
      owner = "rofl0r";
      repo = "microsocks";
      rev = "v1.0.3";
      fetchSubmodules = true;
      sha256 = "sha256-l+8+zqeY/Qf5pKvzW9WQBfltEvrD7Vp+hJAXM2o16aI=";
    });
  };
  mmdb-ipip = {
    pname = "mmdb-ipip";
    version = "6b771abfc889d78857b5d65364c2346ca2db30d1";
    src = fetchgit {
      url = "https://github.com/alecthw/mmdb_china_ip_list.git";
      rev = "6b771abfc889d78857b5d65364c2346ca2db30d1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-rFkuETKHbTaviwPf99Tx9O9FTzVZ73ZD4MxhfxPgTBE=";
    };
  };
  motrix = {
    pname = "motrix";
    version = "1.6.11";
    src = fetchurl {
      url = "https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11.AppImage";
      sha256 = "sha256-tE2Q7NM+cQOg+vyqyfRwg05EOMQWhhggTA6S+VT+SkM=";
    };
  };
  nali = {
    pname = "nali";
    version = "v0.3.2";
    src = fetchFromGitHub ({
      owner = "zu1k";
      repo = "nali";
      rev = "v0.3.2";
      fetchSubmodules = true;
      sha256 = "sha256-iRLoUBA+Kzv1/LZQ8HCvR79K1riYErxEWhB0OmvFy2g=";
    });
  };
  netbird = {
    pname = "netbird";
    version = "v0.8.10";
    src = fetchFromGitHub ({
      owner = "netbirdio";
      repo = "netbird";
      rev = "v0.8.10";
      fetchSubmodules = true;
      sha256 = "sha256-Re/tcS9aZhMtMuUIVrDLjTM8stm7LE6VF5H4EEmcqq4=";
    });
  };
  netmaker = {
    pname = "netmaker";
    version = "v0.14.6";
    src = fetchFromGitHub ({
      owner = "gravitl";
      repo = "netmaker";
      rev = "v0.14.6";
      fetchSubmodules = false;
      sha256 = "sha256-rLIrc8Jm89dEyH/UJzXaHU59tegfQhMGc1E0SWMSPUU=";
    });
  };
  netmaker-ui = {
    pname = "netmaker-ui";
    version = "v0.14.6";
    src = fetchurl {
      url = "https://github.com/gravitl/netmaker-ui/releases/download/v0.14.6/Netmaker-ui-v0.14.6.zip";
      sha256 = "sha256-jTDScIyqMsyYVs598ZwzRZ7sZOCSWOqzz5CJcIQ+cd0=";
    };
  };
  pufferpanel = {
    pname = "pufferpanel";
    version = "v2.5.1";
    src = fetchFromGitHub ({
      owner = "PufferPanel";
      repo = "PufferPanel";
      rev = "v2.5.1";
      fetchSubmodules = true;
      sha256 = "sha256-GrMqZGvPOyPvUAheR4ybEJDWrQ7WukioPFnyrSNDmSA=";
    });
  };
  realm = {
    pname = "realm";
    version = "v2.4.1";
    src = fetchFromGitHub ({
      owner = "zhboner";
      repo = "realm";
      rev = "v2.4.1";
      fetchSubmodules = true;
      sha256 = "sha256-G92SxJE8cv8ATWt9UfQoBYCdo13/V/wqMlGfO6FI8/k=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./realm-v2.4.1/Cargo.lock;
      outputHashes = { };
    };
  };
  simple-obfs = {
    pname = "simple-obfs";
    version = "v0.0.5";
    src = fetchFromGitHub ({
      owner = "shadowsocks";
      repo = "simple-obfs";
      rev = "v0.0.5";
      fetchSubmodules = true;
      sha256 = "sha256-xNkIAltV+NnV+kgKZv8UZaeefjaVt35m+UjU+gbDQEw=";
    });
  };
  sunshine = {
    pname = "sunshine";
    version = "v0.11.1";
    src = fetchFromGitHub ({
      owner = "loki-47-6F-64";
      repo = "sunshine";
      rev = "v0.11.1";
      fetchSubmodules = true;
      sha256 = "sha256-YrQHHpw7GOcdlnyJI28VShYFrTRq7kpILnkyCYf77NE=";
    });
  };
  trojan-go = {
    pname = "trojan-go";
    version = "v0.10.6";
    src = fetchFromGitHub ({
      owner = "p4gefau1t";
      repo = "trojan-go";
      rev = "v0.10.6";
      fetchSubmodules = true;
      sha256 = "sha256-ZzIEKyLhHwYEWBfi6fHlCbkEImetEaRewbsHQEduB5Y=";
    });
  };
  tun2socks = {
    pname = "tun2socks";
    version = "v2.4.1";
    src = fetchFromGitHub ({
      owner = "xjasonlyu";
      repo = "tun2socks";
      rev = "v2.4.1";
      fetchSubmodules = true;
      sha256 = "sha256-FBYRqxS8DJbIc8j8X6WNxl6a1YRcNrPSnNfrq/Y0fMM=";
    });
  };
  vouch = {
    pname = "vouch";
    version = "v0.37.3";
    src = fetchFromGitHub ({
      owner = "vouch";
      repo = "vouch-proxy";
      rev = "v0.37.3";
      fetchSubmodules = true;
      sha256 = "sha256-zXt1Xo6xq1g1putx4q6z7SEXK4lNGRgRnNPXajL5Znw=";
    });
  };
  vpncloud = {
    pname = "vpncloud";
    version = "v2.3.0";
    src = fetchFromGitHub ({
      owner = "dswd";
      repo = "vpncloud";
      rev = "v2.3.0";
      fetchSubmodules = true;
      sha256 = "sha256-74ohjWnBHr31sM08ghFWnrfIRjfQ5M7nrKi0yT/cGEo=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./vpncloud-v2.3.0/Cargo.lock;
      outputHashes = { };
    };
  };
  wechat-uos = {
    pname = "wechat-uos";
    version = "2.1.3";
    src = fetchurl {
      url = "https://home-store-packages.uniontech.com/appstore/pool/appstore/c/com.tencent.weixin/com.tencent.weixin_2.1.3_amd64.deb";
      sha256 = "sha256-W3ckVWbmgpwrIjsEFz80wcN853CdIu1NiiR1czjPsKM=";
    };
  };
  wgcf = {
    pname = "wgcf";
    version = "v2.2.15";
    src = fetchFromGitHub ({
      owner = "ViRb3";
      repo = "wgcf";
      rev = "v2.2.15";
      fetchSubmodules = true;
      sha256 = "sha256-tUEeczs3J//2ZrZkAsSn3C+GScRPaIgheRM2wByS8p4=";
    });
  };
  winbox = {
    pname = "winbox";
    version = "3.37";
    src = fetchurl {
      url = "https://download.mikrotik.com/winbox/3.37/winbox64.exe";
      sha256 = "sha256-q+aW5FgJ8msDIJJqABTTCI3MWsQ9VTorek4l9UoEdDk=";
    };
  };
  yacd = {
    pname = "yacd";
    version = "v0.3.6";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/releases/download/v0.3.6/yacd.tar.xz";
      sha256 = "sha256-YIx+IcHubP7mJoxaOVGkwh3EB+6mcEkFjOwpnAsR4vs=";
    };
  };
  yesplaymusic = {
    pname = "yesplaymusic";
    version = "0.4.5";
    src = fetchurl {
      url = "https://github.com/qier222/YesPlayMusic/releases/download/v0.4.5/YesPlayMusic-0.4.5.AppImage";
      sha256 = "sha256-9Jj4VqrEIsx2oFUoQaPEKaEcyKDR5SQF9tJ2r2w62CM=";
    };
  };
}
