name: Build
on:
  push:

jobs:
  test:
    name: Build Cache
    runs-on: nixos
    steps:
    - uses: actions/checkout@v2

    - name: Auth CachIX
      run: |
        cachix authtoken ${{ secrets.CACHIX_TOKEN }}

    - name: Build all packages
      run: |
        bash build-cache.bash
