name: Deploy
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210207_fd6eaa1/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Format nix files
      run: |
        nix-env -i nixpkgs-fmt -f '<nixpkgs>'
        nixpkgs-fmt --check .

    - name: Flake check
      run: nix flake check
