name: NVFetcher
on:
  push:
  schedule:
    # Every hour
    - cron:  '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@master
      with:
        nix_path: nixpkgs=channel:master
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.8.0pre20220408_a52e369/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://indexyz.cachix.org https://cache.nixos.org/
          trusted-public-keys = indexyz.cachix.org-1:biBEnuZ4vTSsVMr8anZls+Lukq8w4zTHAK8/p+fdaJQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - name: Cache shake database
      uses: actions/cache@v2
      with:
        path: |
          _build/.shake.*
        key: nvfecher-database-${{ hashFiles('**/nvfetcher.toml') }}-${{ github.run_id }}
        restore-keys: |
          nvfecher-database-${{ hashFiles('**/nvfetcher.toml') }}-


    - name: Check Package
      run: |
        nix develop -c -- nvfetcher build -o _build | grep -v '^#' > changelog.tmp
        nix develop -c -- nixpkgs-fmt .

    - name: Output changelog
      id: changelog
      run: |
        CHANGELOG=$(cat changelog.tmp)
        CHANGELOG="${CHANGELOG//'%'/'%25'}"
        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
        echo "::set-output name=changelog::$CHANGELOG"

    - name: Update flake
      run: |
        nix flake update

    - name: Create Pull Request
      if: ${{ steps.changelog.outputs.changelog != 'Up to date' }}
      uses: peter-evans/create-pull-request@v3
      with:
        delete-branch: true
        title: Output Update
        labels: |
          automated/nvfetcher
        body: |
          # NVFetcher output
          ```
          ${{ steps.changelog.outputs.changelog }}
          ```
